#!/bin/sh
org-code-javabuilder/gradlew verGJF -p org-code-javabuilder
LINT_RESULT=$?
org-code-javabuilder/gradlew test -p org-code-javabuilder
TEST_RESULT=$?

RED='\033[0;31m'

# return 1 exit code if running checks fails
[ $LINT_RESULT -ne 0 ] && echo "${RED}\nJava linting errors were detected. These can be fixed by running 'gradle goJF'\n" && exit 1
[ $TEST_RESULT -ne 0 ] && echo "${RED}\nSome tests failed. Run 'org-code-javabuilder/gradlew test' to see which tests failed.\n" && exit 1
exit 0
