AllCops:
  DisplayCopNames: true
  NewCops: disable
  TargetRubyVersion: 2.7

# Disabled rules from code-dot-org's (very old/unchanging) "to do" list
# that we are violating.
# Copied from here:
# https://github.com/code-dot-org/code-dot-org/blob/a4da178625f23f7817027196eecf2971e2b83048/.rubocop_todo.yml

Style/MixinUsage:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# Disabled rules inherited from Hound CI (a legacy code-dot-org CI tool)
# that we are violating.
# Copied from here:
# https://github.com/code-dot-org/code-dot-org/blob/a4da178625f23f7817027196eecf2971e2b83048/.rubocop_hound.yml

Metrics/MethodLength:
  Description: Avoid methods longer than 10 lines of code.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#short-methods
  Enabled: false
  CountComments: false
  Max: 10

Metrics/ClassLength:
  Description: Avoid classes longer than 100 lines of code.
  Enabled: false
  CountComments: false
  Max: 100

Style/Documentation:
  Description: Document classes and non-namespace modules.
  Enabled: false

Metrics/CyclomaticComplexity:
  Description: A complexity metric that is strongly correlated to the number of test
    cases needed to validate a method.
  Enabled: false
  Max: 6

Metrics/PerceivedComplexity:
  Description: A complexity metric geared towards measuring complexity for a human
    reader.
  Enabled: false
  Max: 7

# Copying code-dot-org style overrides that were explicitly chosen.
# Copied from here:
# https://github.com/code-dot-org/code-dot-org/blob/a4da178625f23f7817027196eecf2971e2b83048/.rubocop.yml

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/DotPosition:
  EnforcedStyle: trailing

Style/EmptyElse:
  EnforcedStyle: empty

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Style/EmptyMethod:
  EnforcedStyle: expanded

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Style/NumericLiterals:
  MinDigits: 7

Style/Semicolon:
  AllowAsExpressionSeparator: true

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: no_space
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/WordArray:
  MinSize: 5

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BarePercentLiterals:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrivialAccessors:
  AllowDSLWriters: true

Style/SymbolArray:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
