AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Javabulder CI/CD dependencies
    
Resources:

  # The Artifact Store holds artifacts from codebuild/pipeline so they can be passed
  # from one stage of a pipeline to the next, or so artifacts can be reviewed.
  # We use a single bucket, though multiple instances of the pipeline may exist.
  ArtifactStore:
    Type: AWS::S3::Bucket

  # This role will be used by CodeBuild to execute the CI build. Here we have
  # the common policy rules required. Since we may want to create multiple
  # codebuild projects for different branches, we can append policies when those
  # stack resources are created (in "2-cicd/cicd.template.yml")
  JavabuilderCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: ['sts:AssumeRole']
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
                - codepipeline.amazonaws.com
        Version: '2012-10-17'
      Path: /service-role/
      PermissionsBoundary: !ImportValue IAM-DevPermissions
      Policies:
        - PolicyName: JavabuilderPassRole
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: iam:PassRole
                Resource: !Sub arn:aws:iam::${AWS::AccountId}:role/admin/CloudFormationService
        - PolicyName: JavabuilderCodePipelinePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - "cloudformation:DescribeStacks"
                  - "cloudformation:CreateStack"
                  - "cloudformation:UpdateStack"
                Resource: "*"
        - PolicyName: CodeBuildResourcesAccess
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*"
              - Effect: Allow
                Action:
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                Resource:
                  - !Sub arn:aws:s3:::${ArtifactStore}
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:GetObject
                  - s3:GetObjectVersion
                Resource:
                  - !Sub arn:aws:s3:::${ArtifactStore}/*
              - Effect: Allow
                Action: codestar-connections:UseConnection
                Resource:
                  - !Sub arn:aws:codestar-connections:us-east-1:${AWS::AccountId}:connection/*

  # This role will be used by CodeBuild to verify pull requests. As such it has
  # very limited permissions, as any GitHub user can create a Pull Requests.
  PublicCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: ['sts:AssumeRole']
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
        Version: '2012-10-17'
      Path: /service-role/
      PermissionsBoundary: !ImportValue IAM-DevPermissions
      Policies:
        # - PolicyName: CloudformationPackage
        #   PolicyDocument:
        #     Statement:
        #       - Effect: Allow
        #         Action:
        #           - TBD
        #         Resource: TBD
        - PolicyName: CodeBuildResourcesAccess
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                Resource:
                  - !Sub arn:aws:s3:::${ArtifactStore}
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:GetObject
                  - s3:GetObjectVersion
                Resource:
                  - !Sub arn:aws:s3:::${ArtifactStore}/*

Outputs:
  JavabuilderCodeBuildArtifactBucket:
    Description: Javabuilder CodeBuild Artifact Bucket Name
    Value: !Ref ArtifactStore
    Export: {Name: JavabuilderCodeBuildArtifactBucket}
  JavabuilderCodeBuildRoleArn:
    Description: Javabuilder CodeBuild Role ARN
    Value: !GetAtt JavabuilderCodeBuildRole.Arn
    Export: {Name: JavabuilderCodeBuildRoleArn}
  JavabuilderCodeBuildRoleName:
    Description: Javabuilder CodeBuild Role Name
    Value: !Ref JavabuilderCodeBuildRole
    Export: {Name: JavabuilderCodeBuildRoleName}
  JavabuilderPublicCodeBuildRoleArn:
    Description: Javabuilder Public CodeBuild Role ARN
    Value: !GetAtt PublicCodeBuildRole.Arn
    Export: {Name: JavabuilderPublicCodeBuildRoleArn}
  JavabuilderPublicCodeBuildRoleName:
    Description: Javabuilder Public CodeBuild Role Name
    Value: !Ref PublicCodeBuildRole
    Export: {Name: JavabuilderPublicCodeBuildRoleName}
