AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Javabulder Continuous Integration pipeline

Parameters:
  GitHubOwner:
    Type: String
    Description: GitHub repository owner
    Default: code-dot-org
  GitHubRepo:
    Type: String
    Description: GitHub repository name
    Default: javabuilder
  GitHubBranch:
    Type: String
    Description: The branch that these resources test and deploy. Not necessarily `main`.
    Default: main
  GitHubBadgeEnabled:
    Type: String
    Description: Whether to report back to github the status of build projects
    Default: true
    AllowedValues: [true, false]
  CodeStarConnectionResourceId:
    Type: String
    Description: The Resource Id component of the CodeStar connection ARN for the code-dot-org GitHub repository
    Default: 7df08bcf-9883-42e8-8f5e-d083419d4fe9

Resources:

  # The Elastic Container Registry Repository will store our built docker
  # images, for example, the load-test docker image.
  EcrRepository:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Sub javabuilder-${GitHubBranch}
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement: 
          - 
            Sid: AllowDeveloperPushPull
            Effect: Allow
            Principal: 
              AWS: 
                - !ImportValue JavabuilderCodeBuildRoleArn
                - !Sub "arn:aws:iam::${AWS::AccountId}:role/admin/Developer"
            Action: 
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"

  EncryptionKey:
    Type: 'AWS::KMS::Key'
    Properties:
      Description: encryption key for javabuilder cicd artifacts
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: Ensure root user access
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow administration of the key
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:role/admin/Developer
            Action:
              - 'kms:Create*'
              - 'kms:Describe*'
              - 'kms:Enable*'
              - 'kms:List*'
              - 'kms:Put*'
              - 'kms:Update*'
              - 'kms:Revoke*'
              - 'kms:Disable*'
              - 'kms:Get*'
              - 'kms:Delete*'
              - 'kms:ScheduleKeyDeletion'
              - 'kms:CancelKeyDeletion'
            Resource: '*'
          - Sid: Allow use of the key
            Effect: Allow
            Principal:
              AWS: !ImportValue JavabuilderCodeBuildRoleArn
            Action:
              - 'kms:DescribeKey'
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey'
              - 'kms:GenerateDataKeyWithoutPlaintext'
            Resource: '*'

  # The CodeBuild Project is triggered by pull requests targeting $GitHubBranch
  # It will perform any steps defined in the pr-buildspec.yml file.
  PullRequestBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}-${GitHubBranch}-pr-build
      ServiceRole: !ImportValue JavabuilderCodeBuildRoleArn
      BadgeEnabled: !Ref GitHubBadgeEnabled
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: ARTIFACT_STORE
            Value: !ImportValue JavabuilderCodeBuildArtifactBucket
          - Name: ECR_REPOSITORY
            Value: !GetAtt EcrRepository.RepositoryUri
      Cache:
        Type: LOCAL
        Modes:
          - LOCAL_CUSTOM_CACHE
          - LOCAL_DOCKER_LAYER_CACHE
      Source:
        Type: GITHUB
        Location: !Sub https://github.com/${GitHubOwner}/${GitHubRepo}.git
        BuildSpec: cicd/3-app/javabuilder/pr-buildspec.yml
        ReportBuildStatus: true
      SourceVersion: !Ref GitHubBranch
      Artifacts:
        # We're uplading artifacts manually, to organize by branch.
        Type: NO_ARTIFACTS
      Triggers:
        Webhook: true
        FilterGroups:
          - - Pattern: !Sub ^refs/heads/${GitHubBranch}$
              Type: BASE_REF
            - Pattern: PULL_REQUEST_CREATED,PULL_REQUEST_UPDATED,PULL_REQUEST_REOPENED
              Type: EVENT
  
  # The CodeBuild Project is used in the CodePipeline pipeline to prepare for a release.
  # It will perform any steps defined in the referenced buildspec.yml file.
  LoadTestBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}-load-test-build
      ServiceRole: !ImportValue JavabuilderCodeBuildRoleArn
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: ARTIFACT_STORE
            Value: !ImportValue JavabuilderCodeBuildArtifactBucket
          - Name: ECR_REPOSITORY
            Value: !GetAtt EcrRepository.RepositoryUri
      Source:
        Type: CODEPIPELINE
        BuildSpec: cicd/3-app/load-test/load-test.buildspec.yml
      Artifacts:
        Type: CODEPIPELINE
  
  # The CodeBuild Project is used in the CodePipeline pipeline to prepare for a release.
  # It will perform any steps defined in the referenced buildspec.yml file.
  AppBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}-app-build
      ServiceRole: !ImportValue JavabuilderCodeBuildRoleArn
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: ARTIFACT_STORE
            Value: !ImportValue JavabuilderCodeBuildArtifactBucket
          - Name: ECR_REPOSITORY
            Value: !GetAtt EcrRepository.RepositoryUri
      Source:
        Type: CODEPIPELINE
        BuildSpec: cicd/3-app/javabuilder/buildspec.yml
      Artifacts:
        Type: CODEPIPELINE

  IntegrationTestBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}-integration-test
      ServiceRole: !ImportValue JavabuilderCodeBuildRoleArn
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        PrivilegedMode: true
      Source:
        Type: CODEPIPELINE
        BuildSpec: cicd/3-app/javabuilder/integration-test-buildspec.yml
      Artifacts:
        Type: CODEPIPELINE

  # Grant the Javabuilder CodeBuild Role additional permissions for resources in
  # this template. This allows us to avoid granting permission to * resources.
  JavabuilderRolePolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: root
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - codebuild:*
            Resource:
              - !GetAtt LoadTestBuildProject.Arn
              - !GetAtt AppBuildProject.Arn
          - Effect: Allow
            Action:
              - codebuild:CreateReportGroup
              - codebuild:CreateReport
              - codebuild:UpdateReport
              - codebuild:BatchPutTestCases
              - codebuild:BatchPutCodeCoverage
            Resource:
              - !Sub arn:aws:codebuild:us-east-1:165336972514:report-group/${AWS::StackName}-${GitHubBranch}-pr-build
      Roles:
        - !ImportValue JavabuilderCodeBuildRoleName

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties: 
      Name: !Ref AWS::StackName
      RoleArn: !ImportValue JavabuilderCodeBuildRoleArn
      RestartExecutionOnUpdate: true
      ArtifactStore: 
        Type: S3 
        Location: !ImportValue JavabuilderCodeBuildArtifactBucket
        EncryptionKey:
          Id: !Ref EncryptionKey
          Type: KMS
      Stages: 
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Provider: CodeStarSourceConnection
                Owner: AWS
                Version: 1
              OutputArtifacts:
                - Name: sourceCode
              Configuration:
                ConnectionArn: !Sub arn:aws:codestar-connections:us-east-1:${AWS::AccountId}:connection/${CodeStarConnectionResourceId}
                FullRepositoryId: !Sub ${GitHubOwner}/${GitHubRepo}
                # BranchName: !Ref GitHubBranch
                BranchName: create-codepipeline
                DetectChanges: true
                # OAuthToken: '{{resolve:secrets-manager:DeployCodeOrg-GitHub-OAuthToken}}'
        - Name: Build
          Actions:
            - Name: load-test-build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: sourceCode
              Configuration:
                ProjectName: !Ref LoadTestBuildProject
              OutputArtifacts:
                - Name: loadTestBuildResults
            - Name: app-build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: sourceCode
              Configuration:
                ProjectName: !Ref AppBuildProject
              OutputArtifacts:
                - Name: appBuildResults
        - Name: Deploy_To_Test
          Actions:
            - Name: app-deploy
              ActionTypeId: 
                Category: Deploy 
                Owner: AWS 
                Version: 1 
                Provider: CloudFormation
              InputArtifacts:
                - Name: appBuildResults
              Configuration:
                # StackName: !Sub javabuilder-${GitHubBranch}
                StackName: javabuilder-create-codepipeline
                ActionMode: CREATE_UPDATE
                TemplatePath: appBuildResults::cicd/3-app/javabuilder/template.yml
                TemplateConfiguration: appBuildResults::cicd/3-app/javabuilder/test.config.json
                RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/admin/CloudFormationService
            - Name: integration-test
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: sourceCode
              Configuration:
                ProjectName: !Ref IntegrationTestBuildProject
              OutputArtifacts:
                - Name: integrationTestResultsPOC
        - Name: Integration_Test
          Actions:
            - Name: integration-test
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: sourceCode
              Configuration:
                ProjectName: !Ref IntegrationTestBuildProject
              OutputArtifacts:
                - Name: integrationTestResults

