AWSTemplateFormatVersion: 2010-09-09
Description: The template used to create the required services for load testing
Parameters:
  LoadTestImage:
    Type: String
    Description: Load testing docker image. This should be the full name of the image.
Resources:
  ECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      CapacityProviders:
        - FARGATE
      ClusterName: !Sub "${AWS::StackName}-cluster"
      ClusterSettings:
        - Name: containerInsights
          Value: disabled
      Configuration:
        ExecuteCommandConfiguration:
          Logging: DEFAULT
  CloudwatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "ECSLogGroup-${AWS::StackName}"
      RetentionInDays: 14
  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    DependsOn:
      - ECSCluster
    Properties: 
      Family: !Sub "${AWS::StackName}-task"
      ContainerDefinitions: 
        - Name: javabuilder-load-test
          Image: !Ref LoadTestImage
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:  !Ref CloudwatchLogsGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix:  !Sub "${AWS::StackName}-task"
          Ulimits:
            - HardLimit: 4096
              Name: nofile
              SoftLimit: 4096
      Cpu: 2048
      ExecutionRoleArn: !Ref ExecutionRole
      Memory: 4096
      NetworkMode: awsvpc
      RuntimePlatform: 
        OperatingSystemFamily: LINUX
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: ['sts:AssumeRole']
            Effect: Allow
            Principal: {Service: [ecs-tasks.amazonaws.com]}
      PermissionsBoundary: !ImportValue IAM-DevPermissions
      ManagedPolicyArns:
        # AWS-managed policy for executing an ECS task
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
