version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - cd ./integration-tests
      - npm install
  build:
    commands:
      - set -e

      - ls

      - # TODO: Make the ARN and/or secret names configurable too?
      - private_key=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:us-east-1:475661607190:secret:development/cdo/javabuilder_private_key-gZE3SO)
      - password=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:us-east-1:475661607190:secret:development/cdo/javabuilder_key_password-J1RILi)

      - # TODO: Make these configurable
      - sub_domain=javabuilder-test
      - base_domain=code.org

      - JAVABUILDER_PRIVATE_KEY=$private_key \
      - JAVABUILDER_PASSWORD=$password \
      - JAVABUILDER_HTTP_URL=https://"$sub_domain"-http."$base_domain"/seedsources/sources.json \
      - JAVABUILDER_WEBSOCKET_URL=wss://"$sub_domain"."$base_domain" \
      - npm test
