version: 0.2
phases:
  install:
    runtime-versions:
      ruby: 2.7
      java: corretto11
      python: 3.8
    commands:
      - rbenv versions
      # downgrade from default codebuild ruby runtime to the version we specify in .ruby-version, if different
      - rbenv install -s
      - ruby -v
      - gem install bundler -v 2.4.22
      - pip install cfn-lint

  build:
    # This should be moved to a shell script if it gets more complicated.
    commands:
      - set -e
      - BRANCH_NAME=${CODEBUILD_WEBHOOK_HEAD_REF#"refs/heads/"}
      - ARTIFACT_PATH=branch/$BRANCH_NAME/$CODEBUILD_BUILD_NUMBER

      - cfn-lint cicd/1-setup/*.template.yml
      - cfn-lint cicd/2-cicd/*.template.yml

      - cd ./javabuilder-authorizer
      - ./build.sh

      - cd $CODEBUILD_SRC_DIR
      - cd org-code-javabuilder
      - ./gradlew test
      - ./build.sh

      - cd $CODEBUILD_SRC_DIR
      - cd api-gateway-routes
      - rake test
      - cd $CODEBUILD_SRC_DIR
      - cd javabuilder-authorizer
      - rake test

      - cd $CODEBUILD_SRC_DIR
      - erb -T - cicd/3-app/javabuilder/template.yml.erb > app-template.yml
      - cat app-template.yml
      - cfn-lint app-template.yml
      - aws cloudformation package --template-file app-template.yml --output-template-file cloudformation-output.yml --s3-bucket $ARTIFACT_STORE --s3-prefix "$ARTIFACT_PATH/cloudformation-package"
      - aws s3 cp cloudformation-output.yml "s3://${ARTIFACT_STORE}/${ARTIFACT_PATH}/"
      - echo "Artifacts uploaded to S3, view them at https://console.aws.amazon.com/s3/buckets/${ARTIFACT_STORE}?region=us-east-1&prefix=${ARTIFACT_PATH}/"
