package org.code.validation;

/**
 * User-facing class that runs the main method of a student's project and returns the
 * NeighborhoodLog generated by that project. If the student project does not use any neighborhood
 * actions, it will return an empty NeighborhoodLog.
 */
public class NeighborhoodTestRunner {
  public static NeighborhoodLog run() {
    // TODO: implement this method (https://codedotorg.atlassian.net/browse/JAVA-413)
    return null;
  }
}
