version: 0.2
phases:
  install:
    runtime-versions:
      ruby: 2.7
      java: corretto11
      python: 3.8
    commands:
      - gem install bundler
      - pip install cfn-lint
  build:
    commands:
      - set -e
      - pwd
      - ls
      - echo Hello from buildspec
      - ls cicd/3-app
      - erb -T - cicd/3-app/template.yml.erb > cicd/3-app/template.yml
      - ls cicd/3-app
      - ./javabuilder-authorizer/build.sh
      - ./org-code-javabuilder/build.sh