package org.code.validation;

import org.code.protocol.JavabuilderContext;
import org.code.validation.support.ValidationProtocol;

/**
 * User-facing class that runs the main method of a student's project and returns the
 * NeighborhoodLog generated by that project. If the student project does not use any neighborhood
 * actions, it will return an empty NeighborhoodLog.
 */
public class NeighborhoodTestRunner {
  public static NeighborhoodLog run() {
    ValidationProtocol protocolInstance =
        (ValidationProtocol) JavabuilderContext.getInstance().get(ValidationProtocol.class);
    protocolInstance.invokeMainMethod();
    return protocolInstance.getNeighborhoodLog();
  }
}
