package org.code.protocol;

/** A status message directed to the client-side terminal, generated by Javabuilder. */
public class StatusMessage extends ClientMessage {
  public StatusMessage(StatusMessageKey status) {
    super(ClientMessageType.STATUS, status.toString());
  }
}
