package org.code.protocol;

public enum StatusMessageKey {
  COMPILING,
  COMPILATION_SUCCESSFUL,
  RUNNING,
  RUNNING_VALIDATION,
  RUNNING_PROJECT_TESTS,
  NO_TESTS_FOUND,
  GENERATING_RESULTS,
  GENERATING_PROGRESS,
  SENDING_VIDEO,
  TIMEOUT_WARNING,
  TIMEOUT,
  EXITED
}
