package org.code.protocol;

public enum StatusMessageKey {
  COMPILING,
  COMPILATION_SUCCESSFUL,
  RUNNING,
  GENERATING_RESULTS,
  GENERATING_PROGRESS,
  SENDING_VIDEO,
  TIMEOUT_WARNING,
  TIMEOUT,
  EXITED
}
