package org.code.protocol;

import java.util.HashMap;

/** A status message directed to the client-side terminal, generated by Javabuilder. */
public class StatusMessage extends ClientMessage {
  public StatusMessage(StatusMessageKey status) {
    super(ClientMessageType.STATUS, status.toString());
  }

  public StatusMessage(StatusMessageKey status, HashMap<String, String> detail) {
    super(ClientMessageType.STATUS, status.toString(), detail);
  }
}
